GET http://localhost:8001/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/hello
Accept: application/json
###
GET http://localhost:8000/user-service/user/count
Accept: application/json
token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE2OTY2NzcxMDAsInBob25lIjoiMTM5NTE5MDUxNzEiLCJpZCI6MSwiZXhwIjoxNjk2Nzc3MTAwLCJpYXQiOjE2OTY2NzcxMDB9.N5Ca3xKm3OEgw6nmkjnKWSEIdH6qSWnQS3guqB77zrM


###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json

{
  "phone": "13951905171",
  "password": "123123"
}

###
POST http://localhost:8000/user-service/user/register
Content-Type: application/json

{
  "phone": "13951905172",
  "password": "888888"
}