version: '3'
services:
  springboot-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/user-center?useSSL=false
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root

      MYSQL_DATABASE: user_center
    ports:
      - "3308:3306"